language: php
sudo: false
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
script:
- echo 'Tested'
before_deploy:
      - git config --local user.name "artikus11"
      - git config --local user.email "artikus.sol@gmail.ru"
      - git tag "1.0.0"

after_deploy: "release created"