name: ainsys-connector-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build project
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create deployment artifact
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: ${{ github.workflow }}.zip
          exclusions: '*.git* /*node_modules/* .editorconfig /*src/* .eslintrc.json .prettierrc.json gulpfile.js .stylelintrc.json package.json package-lock.json'
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.workflow }}
          path: ${{ github.workflow }}.zip
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.workflow }}
      - name: Get Changelog Entry
        id: changelog-reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: CHANGELOG.md
      - name: Create Release
        id: create-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.changelog-reader.outputs.version }}
      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ github.workflow }}.zip
          asset_name: ${{ github.workflow }}.zip
          asset_content_type: application/zip